#!/usr/bin/env php
<?php

use Symfony\Component\Console\Input\ArgvInput;

define('LARAVEL_START', microtime(true));

require __DIR__.'/vendor/autoload.php';

$app = require_once __DIR__.'/bootstrap/app.php';

Statamic\Console\Please\Application::rebindKernel();

$status = $app->handleCommand(new ArgvInput);

exit($status);
